#!/bin/bash

# Cleanup script for exp_traffic_v2 experiment artifacts
# Removes all generated files to allow re-running experiments

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default options
FORCE=false
DRY_RUN=false

# Script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Define paths to clean (relative to project root)
DATASET_DIR="${PROJECT_ROOT}/train_test_data/exp_traffic_v2"
MODEL_DIR="${PROJECT_ROOT}/model/exp_traffic_v2"
EVAL_DIR="${PROJECT_ROOT}/evaluation_results/exp_traffic_v2"
LOG_PATTERN="${PROJECT_ROOT}/log/exp_traffic_v20_*.log"

# Function to display usage
usage() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS]

Clean all artifacts generated by exp_traffic_v2 experiments.

OPTIONS:
    --force      Skip confirmation prompt
    --dry-run    Show what would be deleted without actually deleting
    --help       Display this help message

ARTIFACTS TO BE CLEANED:
    - Dataset files:     train_test_data/exp_traffic_v2/
    - Model files:       model/exp_traffic_v2/
    - Evaluation results: evaluation_results/exp_traffic_v2/
    - Log files:         log/exp_traffic_v2_*.log

EXAMPLES:
    $(basename "$0")           # Interactive mode with confirmation
    $(basename "$0") --force   # Skip confirmation
    $(basename "$0") --dry-run # Show what would be deleted

EOF
}

# Function to print colored messages
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check if a path exists
path_exists() {
    local path="$1"
    if [[ -d "$path" ]] || [[ -f "$path" ]] || [[ $(ls $path 2>/dev/null) ]]; then
        return 0
    fi
    return 1
}

# Function to remove directory or files
remove_path() {
    local path="$1"
    local path_type="$2"

    if path_exists "$path"; then
        if [[ "$DRY_RUN" == true ]]; then
            print_info "Would remove: $path ($path_type)"
        else
            print_info "Removing: $path ($path_type)"
            rm -rf "$path"
            if [[ $? -eq 0 ]]; then
                print_info "Successfully removed: $path"
            else
                print_error "Failed to remove: $path"
                return 1
            fi
        fi
    else
        print_warning "Path does not exist (skipping): $path"
    fi
    return 0
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --force)
            FORCE=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help)
            usage
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# Print header
echo "========================================"
echo "  exp_traffic_v2 Cleanup Script"
echo "========================================"
echo ""

# Show mode
if [[ "$DRY_RUN" == true ]]; then
    print_warning "DRY RUN MODE - No files will be deleted"
    echo ""
fi

# List artifacts that will be cleaned
print_info "Artifacts to be cleaned:"
echo "  1. Dataset files:     $DATASET_DIR"
echo "  2. Model files:       $MODEL_DIR"
echo "  3. Evaluation results: $EVAL_DIR"
echo "  4. Log files:         $LOG_PATTERN"
echo ""

# Count existing artifacts
existing_count=0
if path_exists "$DATASET_DIR"; then ((existing_count++)); fi
if path_exists "$MODEL_DIR"; then ((existing_count++)); fi
if path_exists "$EVAL_DIR"; then ((existing_count++)); fi
if ls $LOG_PATTERN 2>/dev/null >/dev/null; then ((existing_count++)); fi

if [[ $existing_count -eq 0 ]]; then
    print_warning "No exp_traffic_v2 artifacts found to clean"
    exit 0
fi

# Confirmation prompt (unless --force is used)
if [[ "$FORCE" == false ]] && [[ "$DRY_RUN" == false ]]; then
    echo -e "${RED}WARNING: This will permanently delete all exp_traffic_v2 artifacts!${NC}"
    echo ""
    read -p "Are you sure you want to continue? (yes/no): " confirm
    echo ""

    if [[ "$confirm" != "yes" ]] && [[ "$confirm" != "y" ]]; then
        print_info "Cleanup cancelled"
        exit 0
    fi
fi

# Start cleanup
print_info "Starting cleanup..."
echo ""

# Track errors
error_count=0

# 1. Remove dataset directory
remove_path "$DATASET_DIR" "dataset files" || ((error_count++))

# 2. Remove model directory
remove_path "$MODEL_DIR" "model files" || ((error_count++))

# 3. Remove evaluation results directory
remove_path "$EVAL_DIR" "evaluation results" || ((error_count++))

# 4. Remove log files
if ls $LOG_PATTERN 2>/dev/null >/dev/null; then
    if [[ "$DRY_RUN" == true ]]; then
        print_info "Would remove log files matching: $LOG_PATTERN"
    else
        print_info "Removing log files matching: $LOG_PATTERN"
        rm -f $LOG_PATTERN
        if [[ $? -eq 0 ]]; then
            print_info "Successfully removed log files"
        else
            print_error "Failed to remove log files"
            ((error_count++))
        fi
    fi
else
    print_warning "No log files found matching: $LOG_PATTERN"
fi

echo ""
echo "========================================"

# Final status
if [[ "$DRY_RUN" == true ]]; then
    print_info "Dry run completed. No files were deleted."
else
    if [[ $error_count -eq 0 ]]; then
        print_info "Cleanup completed successfully!"
    else
        print_error "Cleanup completed with $error_count error(s)"
        exit 1
    fi
fi

echo "========================================"
